name: base_design
description: Project Design using GET Micro-Framework.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #Core
  get: ^3.11.1
  velocity_x: ^0.4.1
  #Storage
  hive: ^1.4.4
  hive_flutter: ^0.3.1
  #Network
  http: ^0.12.2
  #Icons
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^0.7.2+1
  lint: ^1.0.0
  build_runner:

flutter:
  uses-material-design: true
